title: Delayed Drug Release App
# logo: /images/Film_Design.jpg
description: Python + Chemistry to model and optimize polymer-mediated drug delivery designs (using Pandas, Numpy, Dash, TensorFlow, and scikit-learn libraries)
#show_downloads: true
theme: jekyll-theme-cayman
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
